config/routes.rb
Rails.application.routes.draw do
  # get 'orders', action: :index, controller: :orders
  get 'cart', action: :cart, controller: :orders
  get 'checkout', action: :checkout, controller: :orders
  resources :products
  devise_for :users, controllers: {
    sessions: 'users/sessions', 
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  resources :users, only: [] do
    resource :setting
  end
  resources :orders

  resources :orders, only: [] do
    resources :line_items
  end
  root 'home#index'
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id         :bigint           not null, primary key
#  counter    :integer          default(0)
#  status     :integer          default("in_cart")
#  subtotal   :decimal(8, 2)    default(0.0)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_orders_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Order < ApplicationRecord
  belongs_to :user
  has_many :line_items, dependent: :destroy

  enum status: [:in_cart, :checkout, :confirmed, :to_ship, :shipping, :shipped, :completed, :cancel, :refunded, :pending]

  scope :by_order, -> (order) {
    includes(:line_items).joins(:line_items).where(id: order).first
  }

  scope :except_in_cart, -> { where.not(subtotal: 0) }
  
  def in_cart?(product)
    line_items.find_by(product_id: product).present?
  end

  def line_item(product)
    line_items.find_by(product_id: product)
  end

  def update_order
    update(
      counter: self.line_items.count, 
      subtotal: self.line_items.sum('(price - (price*discount)/100.0) * quantity')
    )
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  add_breadcrumb I18n.t('breadcrumb.home'), :root_path
  add_breadcrumb I18n.t('breadcrumb.orders'), :orders_path

  def index
    @orders = current_user.orders.except_in_cart
  end

  def create
  end

  def cart
    add_breadcrumb I18n.t('breadcrumb.cart')
    @items = @cart.line_items
  end

  def show
    @order = current_user.orders.find_by(id: params[:id])
    @items = @order.line_items
  end

  def checkout
    @cart.checkout!
    redirect_to cart_path
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def currency(num, cls=nil)
    num == 0.0 ? price_contact : n2c(num, cls)
  end

  def order_progress(cart)
    content_tag :div, class: 'w-100 mt-6 mb-5' do
      content_tag :div, class: 'position-relative w-75 m-auto' do
        content_tag :div, class: 'position-relative w-100 ms-10' do
          concat content_tag(:div, progress_tag(cart), class: 'progress height-1')
          concat content_tag(:div, buttons_tag(cart))
        end
      end
    end
  end

  private
  def price_contact
    content_tag :div, t('orders.price_contact'), class: 'text-capitalize text-danger'
  end

  def n2c(num, cls)
    html = cls.nil? ? '<div>%n<sup>%u</sup></div>' : '<div class="price-order-top">%n<sup>%u</sup></div>'
    number_to_currency(
        num*1000, 
        unit: 'đ', 
        format: html.html_safe, 
        separator: '.', 
        delimiter: ','
      ).gsub(/\.0+\</, '<').html_safe
  end

  def buttons_tag(cart)
    html = ''
    start = 0
    ['in_cart', 'checkout', 'confirmed', 'delivering', 'completed'].each do |status|
      html << button_html_tag(status, active_list(cart.status), start, cart)
      start = start + 20
    end
    html.html_safe
  end

  def status_name(status, cart)
    return 'confirm' if [:confirmed].include?(status.to_sym)
    return cart.status if status == 'completed' && [:cancel, :refunded, :pending].include?(cart.status.to_sym)
    status
  end

  def button_html_tag(status, active, start, cart)
    content_tag :button, class: class_names({
      'position-absolute': true,
      'top-0': true,
      'start-0': start == 0,
      'start-20': start == 20,
      'start-40': start == 40,
      'start-60': start == 60,
      'start-80': start == 80,
      'translate-middle': true,
      btn: true,
      'btn-sm': true,
      'btn-success': active.include?(status),
      'btn-secondary': !active.include?(status),
      'rounded-pill': true,
      'button-progress-check': true
    }), type: 'button' do
      concat content_tag(:p, t("orders.#{status_name(status, cart)}"), class: 'progress-title text-capitalize')
      concat content_tag(:i, nil, class: 'fas fa-check')
    end
  end

  def progress_tag(cart)
    content_tag(
      :div, nil, class: progress_class(cart), 
      role: 'progressbar', 'aria-valuenow': value_now(cart.status), 'aria-valuemin': '0', 
      'aria-valuemax': '100'
    )
  end

  def value_now(status)
    key = status.to_sym
    key = :delivering if [:to_ship, :shipping, :shipped].include?(status.to_sym)
    key = :completed if [:cancel, :refunded, :pending].include?(status.to_sym)
    statuses[key][:position]
  end

  def active_list(status)
    key = status.to_sym
    key = :delivering if [:to_ship, :shipping, :shipped].include?(status.to_sym)
    key = :completed if [:cancel, :refunded, :pending].include?(status.to_sym)
    statuses[key][:active]
  end
  
  def statuses
    {
      in_cart: {
        position: 0,
        active: ['in_cart']
      }, 
      checkout: {
        position: 20,
        active: ['in_cart', 'checkout']
      },
      confirmed: {
        position: 40,
        active: ['in_cart', 'checkout', 'confirmed']
      },
      delivering: {
        position: 60,
        active: ['in_cart', 'checkout', 'confirmed', 'delivering']
      },
      completed: {
        position: 80,
        active: ['in_cart', 'checkout', 'confirmed', 'delivering', 'completed']
      }
    }
  end

  def progress_class(cart)
    class_names({
      'progress-bar': true,
      'bg-success': true,
      'in-cart': cart.status == 'in_cart',
      checkout: cart.status == 'checkout',
      confirm: cart.status == 'confirmed',
      delivering: cart.status == 'delivering',
      completed: cart.status == 'completed',
      closed: cart.status == 'closed'
    })
  end
end

app/views/orders/_cart_action.html.erb
<%= render "orders/actions/#{action}" %>

app/views/orders/_cart_detail.html.erb
<div class='order-detail w-60 bg-white me-2'>
  <div class='title d-flex p-1 border-bottom text-center fw-bold text-capitalize'>
    <%['name', 'quantity', 'price'].each do |title| %>
      <div class="<%= title %>">
        <%= t("orders.order.title.#{title}") %>
      </div>
    <% end %>
  </div>
  <div>
    <% items.each do |item| %>
      <div class='order-item d-flex border-bottom p-1'>
        <div class='order-item--thumbnail me-2'>
          <div class='thumbnail lozad' <%=lozad_class(item.product.thumbnail)%>></div>
        </div>
        <div class='order-product--name text-capitalize me-2 text-wrap'>
          <%= link_to product_path(item.product), class: 'text-decoration-none text-black bg-transparent', target: '_top' do %>
            <strong><%= item.product.name %></strong>
          <% end %>
        </div>
        <div class='order-product--stepper me-3'>
          <%= render partial: 'products/stepper', locals: { quantity: quantity(cart, item.product.id), product: item.product, user: current_user }%>
        </div>
        <div class="<%= in_cart(item.product) %>">
          <%= render partial: 'products/price', locals: {product: item.product, for_order: true } %>
        </div>
        <div class='order-product--total fs-4 text-end'>
          <%= currency(item.total) %>
        </div>
        <div class='order-product--actions text-center'>
          <i class="fas fa-trash-alt cursor-pointer"></i>
        </div>
      </div>
    <% end %>
  </div>
  <div class='row'>
    <div class='w-100 justify-content-end text-danger fs-3 px-2-5 py-2 d-flex'>
      <span class='me-2 text-capitalize'><%= t('orders.order.total') %>: </span>
      <%= currency(cart.subtotal) %>
    </div>
  </div>
</div>

app/views/orders/_cart_summary.html.erb
<div class='order-info w-40 bg-transparent'>
  <div class='bg-white mb-3 px-3'>
    <div class='order-delivery lh-2'>
      <div class='d-flex'>
        <div class='w-50 text-capitalize fs-5 '><%= t('orders.order.title.delivery') %></div>
        <div class='w-50 text-capitalize text-end fs-5'><%= t('actions.change') %></div>
      </div>
      <div class='d-flex'>
        <div class='w-50 text-capitalize border-end'>
          <%= current_user.profile.name %>
        </div>
        <div class='w-50 text-capitalize ps-2'>
          <%= current_user.profile.phone %>
        </div>
      </div>
      <div class='w-100 text-capitalize text-muted fs-0-8'>
        <%= current_user.address %>
      </div>
    </div>
  </div>
  <div class='bg-white mb-3 px-3 lh-2'>
    <div class='order-receipt'>
      <div class='d-flex'>
        <div class='w-25 text-capitalize fs-6'>
          <%= t('orders.order.title.subtotal') %>
        </div>
        <div class='w-75 fs-6 text-end'>
          <%= currency(cart.subtotal) %>
        </div>
      </div>
      <div class='d-flex'>
        <div class='w-25 text-capitalize fs-6'>
          <%= t('orders.order.title.promotion') %>
        </div>
        <div class='w-75 fs-6 text-end'>
          <div>0<sup>đ</sup></div>
        </div>
      </div>
      <div class='border-top d-flex'>
        <div class='w-25 text-capitalize fs-6'>
          <%= t('orders.order.total') %>
        </div>
        <div class='w-75 fs-4 text-end text-danger fw-light'>
          <%= currency(cart.subtotal) %>
        </div>
      </div>
    </div>
  </div>
  <%= render partial: 'orders/cart_action', locals: { action: cart.status }%>
</div>

app/views/orders/_show_cart.html.erb
<div id='menu-cart'>
  <%= render 'shared/breadcrumb' %>
  <%= turbo_stream_from "cart-detail" %>
  <%= turbo_frame_tag "cart-detail" do %>
    <%= render partial: 'orders/step_line', locals: {cart: cart} %>
  <% end %>

  <div class="wrapper" data-main-target='main'>
    <div class='container-fluid'>
      <div class='position-relative d-flex w-100'>
        <%= render partial: 'orders/cart_detail', locals: { items: items, cart: cart }%>
        <%= render partial: 'orders/cart_summary', locals: { items: items, cart: cart }%>
      </div>
    </div>
  </div>
</div>

app/views/orders/_step_line.html.erb
<%= order_progress(cart) %>

app/views/orders/cart.html.erb
<% if @items.empty? %>
  <%= render 'shared/show_empty' %>
<% else %>
  <%= render partial: 'orders/show_cart', locals: {items: @items, cart: @cart} %>
<% end %>

app/views/orders/index.html.erb
<%= render 'shared/breadcrumb' %>
<div class='container'>
  <div class='row'>
    <%- @orders.each do |order| %>
      <%= link_to order_path(order), class: 'text-decoration-none text-underline-none' do %>
        <div class='col-xl-12 col-sm-12'>
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
              <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              <a href="#" class="card-link">Card link</a>
              <a href="#" class="card-link">Another link</a>
            </div>
          </div>  
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/orders/show.html.erb
<%= render partial: 'orders/show_cart', locals: {items: @items, cart: @order} %>