config/routes.rb
Rails.application.routes.draw do
  # get 'orders', action: :index, controller: :orders
  get 'cart', action: :cart, controller: :orders
  get 'checkout', action: :checkout, controller: :orders
  resources :products
  devise_for :users, controllers: {
    sessions: 'users/sessions', 
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  resources :users, only: [] do
    resource :setting
  end
  resources :orders

  resources :orders, only: [] do
    resources :line_items
  end
  root 'home#index'
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id         :bigint           not null, primary key
#  counter    :integer          default(0)
#  status     :integer          default("in_cart")
#  subtotal   :decimal(8, 2)    default(0.0)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_orders_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Order < ApplicationRecord
  belongs_to :user
  has_many :line_items, dependent: :destroy

  enum status: [:in_cart, :checkout, :confirmed, :to_ship, :shipping, :shipped, :completed, :cancel, :refunded, :pending]

  scope :by_order, -> (order) {
    includes(:line_items).joins(:line_items).where(id: order).first
  }

  scope :except_in_cart, -> { where.not(subtotal: 0) }
  
  def in_cart?(product)
    line_items.find_by(product_id: product).present?
  end

  def line_item(product)
    line_items.find_by(product_id: product)
  end

  def update_order
    update(
      counter: self.line_items.count, 
      subtotal: self.line_items.sum('(price - (price*discount)/100.0) * quantity')
    )
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  add_breadcrumb I18n.t('breadcrumb.home'), :root_path
  add_breadcrumb I18n.t('breadcrumb.orders'), :orders_path

  def index
    @orders = current_user.orders.except_in_cart
  end

  def create
  end

  def cart
    add_breadcrumb I18n.t('breadcrumb.cart')
    @items = @cart.line_items
  end

  def show
    @order = current_user.orders.find_by(id: params[:id])
    @items = @order.line_items
  end

  def checkout
    @cart.checkout!
    redirect_to cart_path
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def currency(num, cls=nil)
    num == 0.0 ? price_contact : n2c(num, cls)
  end

  def order_progress(cart)
    content_tag :div, class: 'w-100 mt-6 mb-5' do
      content_tag :div, class: 'position-relative w-75 m-auto' do
        content_tag :div, class: 'position-relative w-100 ms-10' do
          concat content_tag(:div, progress_tag(cart), class: 'progress height-1')
          concat content_tag(:div, buttons_tag(cart))
        end
      end
    end
  end

  private
  def price_contact
    content_tag :div, t('orders.price_contact'), class: 'text-capitalize text-danger'
  end

  def n2c(num, cls)
    html = cls.nil? ? '<div>%n<sup>%u</sup></div>' : '<div class="price-order-top">%n<sup>%u</sup></div>'
    number_to_currency(
        num*1000, 
        unit: 'đ', 
        format: html.html_safe, 
        separator: '.', 
        delimiter: ','
      ).gsub(/\.0+\</, '<').html_safe
  end

  def buttons_tag(cart)
    html = ''
    start = 0
    ['in_cart', 'checkout', 'confirmed', 'delivering', 'completed'].each do |status|
      html << button_html_tag(status, active_list(cart.status), start, cart)
      start = start + 20
    end
    html.html_safe
  end

  def status_name(status, cart)
    return 'confirm' if [:confirmed].include?(status.to_sym)
    return cart.status if status == 'completed' && [:cancel, :refunded, :pending].include?(cart.status.to_sym)
    status
  end

  def button_html_tag(status, active, start, cart)
    content_tag :button, class: class_names({
      'position-absolute': true,
      'top-0': true,
      'start-0': start == 0,
      'start-20': start == 20,
      'start-40': start == 40,
      'start-60': start == 60,
      'start-80': start == 80,
      'translate-middle': true,
      btn: true,
      'btn-sm': true,
      'btn-success': active.include?(status),
      'btn-secondary': !active.include?(status),
      'rounded-pill': true,
      'button-progress-check': true
    }), type: 'button' do
      concat content_tag(:p, t("orders.#{status_name(status, cart)}"), class: 'progress-title text-capitalize')
      concat content_tag(:i, nil, class: 'fas fa-check')
    end
  end

  def progress_tag(cart)
    content_tag(
      :div, nil, class: progress_class(cart), 
      role: 'progressbar', 'aria-valuenow': value_now(cart.status), 'aria-valuemin': '0', 
      'aria-valuemax': '100'
    )
  end

  def value_now(status)
    key = status.to_sym
    key = :delivering if [:to_ship, :shipping, :shipped].include?(status.to_sym)
    key = :completed if [:cancel, :refunded, :pending].include?(status.to_sym)
    statuses[key][:position]
  end

  def active_list(status)
    key = status.to_sym
    key = :delivering if [:to_ship, :shipping, :shipped].include?(status.to_sym)
    key = :completed if [:cancel, :refunded, :pending].include?(status.to_sym)
    statuses[key][:active]
  end
  
  def statuses
    {
      in_cart: {
        position: 0,
        active: ['in_cart']
      }, 
      checkout: {
        position: 20,
        active: ['in_cart', 'checkout']
      },
      confirmed: {
        position: 40,
        active: ['in_cart', 'checkout', 'confirmed']
      },
      delivering: {
        position: 60,
        active: ['in_cart', 'checkout', 'confirmed', 'delivering']
      },
      completed: {
        position: 80,
        active: ['in_cart', 'checkout', 'confirmed', 'delivering', 'completed']
      }
    }
  end

  def progress_class(cart)
    class_names({
      'progress-bar': true,
      'bg-success': true,
      'in-cart': cart.status == 'in_cart',
      checkout: cart.status == 'checkout',
      confirm: cart.status == 'confirmed',
      delivering: cart.status == 'delivering',
      completed: cart.status == 'completed',
      closed: cart.status == 'closed'
    })
  end
end

app/views/orders/actions/_cancel.html.erb
  <div class='bg-transparent mb-3 w-100'>
    <p class='first-letter-uppercase text-muted'>
      <%= t('orders.actions.cancel') %>
    </p>
  </div>

app/views/orders/actions/_checkout.html.erb
  <div class='bg-transparent mb-3 w-100'>
    <p class='first-letter-uppercase text-muted'>
      <%= t('orders.waiting_confirm') %>
    </p>
  </div>

app/views/orders/actions/_completed.html.erb
  <div class='bg-transparent mb-3 w-100'>
    <p class='first-letter-uppercase text-muted'>
      <%= t('orders.actions.completed') %>
    </p>
  </div>

app/views/orders/actions/_confirmed.html.erb
  <div class='bg-transparent mb-3 w-100'>
    <p class='first-letter-uppercase text-muted'>
      <%= t('orders.actions.delivery') %>
    </p>
  </div>

app/views/orders/actions/_in_cart.html.erb
  <div class='bg-white mb-3 w-100'>
    <%= link_to t('orders.checkout'), checkout_path, class: "btn btn-danger text-capitalize w-100" %>
  </div>

app/views/orders/actions/_pending.html.erb
  <div class='bg-transparent mb-3 w-100'>
    <p class='first-letter-uppercase text-muted'>
      <%= t('orders.actions.pending') %>
    </p>
  </div>

app/views/orders/actions/_refunded.html.erb
  <div class='bg-transparent mb-3 w-100'>
    <p class='first-letter-uppercase text-muted'>
      <%= t('orders.actions.refunded') %>
    </p>
  </div>

app/views/orders/actions/_shipped.html.erb
  <div class='bg-transparent mb-3 w-100'>
    <p class='first-letter-uppercase text-muted'>
      <%= t('orders.actions.shipped') %>
    </p>
  </div>

app/views/orders/actions/_shipping.html.erb
  <div class='bg-transparent mb-3 w-100'>
    <p class='first-letter-uppercase text-muted'>
      <%= t('orders.actions.shipping') %>
    </p>
  </div>

app/views/orders/actions/_to_ship.html.erb
  <div class='bg-transparent mb-3 w-100'>
    <p class='first-letter-uppercase text-muted'>
      <%= t('orders.actions.to_ship') %>
    </p>
  </div>